name: Docker CI/CD Pipeline (Docker Hub)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  build-scan-push:
    runs-on: [self-hosted, macos, x64]

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=sha,format=short,prefix=
            type=ref,event=branch
            # THIS IS THE CORRECTED SYNTAX
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # We need to explicitly output the tags for the next step to work correctly
          outputs: 'tags=${{ steps.meta.outputs.tags }}'

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          # We now get the tags from the 'build-push-action' output for consistency
          image-ref: ${{ steps.build-and-push.outputs.tags }}
          format: 'github'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'