name: Docker CI/CD Pipeline (Docker Hub)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}
  # Define a specific tag for scanning to avoid issues with multiple tags
  SCAN_IMAGE_TAG: main

jobs:
  build-scan-push:
    # THIS HAS BEEN CORRECTED: Use the appropriate label for your self-hosted Mac runner.
    # The 'linux' label will cause the job to never run on your Mac.
    runs-on: [self-hosted, macos, x64] # Or use 'arm64' if you have an M-series Mac

    permissions:
      contents: read
      security-events: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=sha,format=short,prefix=
            type=ref,event=branch
            # THIS HAS BEEN CORRECTED: The syntax 'type=latest' is invalid.
            # We use 'type=raw,value=latest' to apply a conditional 'latest' tag.
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.SCAN_IMAGE_TAG }}
          format: 'github'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'