name: Docker CI/CD Pipeline (Docker Hub)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  # Correctly constructs the image name using the repository name
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  build-scan-push:
    # Use a self-hosted runner with the appropriate labels
    runs-on: [self-hosted, linux, x64] # Example labels, adjust as needed

    permissions:
      contents: read
      security-events: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=sha,format=short,prefix=
            type=ref,event=branch,enable=${{ github.ref_name == 'main' }}
            type=latest,enable=${{ github.ref_name == 'main' }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          # Use the full registry path to reference the image for scanning
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
          format: 'github'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          # 'fail-on-scans' is not a valid Trivy-action input. Use 'exit-code' instead.
          # The job will fail because of exit-code '1'.